name: Canary

on:
  push:
    branches: [master]

jobs:
  release-canary:
    name: Release Canary Version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: node --version
      - run: npm install
      - run: npm run test-ci
      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run release-canary
