name: Release canary

# Workflow must be dispatched manually
on: [workflow_dispatch]

jobs:
  # Use Lerna to publish canary releases of monorepo packages
  release-canary:
    runs-on: ubuntu-latest
    steps:
      # Check out repo
      - uses: actions/checkout@v2
        with:
          # Fetch all commits so Lerna can version properly
          fetch-depth: 0

      # Set up Node
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      # Output which Node version is used
      - run: node --version

      # Authenticate with NPM registry
      - run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Run whoami to verify authentication was successful
      - run: npm whoami

      # Install and test
      - run: npm install && npm run test-ci

      # Use commit sha to build a preid
      - name: Generate prerelease ID
        run: echo "PREID=$(echo $GITHUB_SHA | cut -c 1-3)" >> $GITHUB_ENV

      # Publish canary packages to npm
      - run: npx lerna publish --force-publish --canary --yes --preid ${{ env.PREID }}
