name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # Test different Node versions
  test-node:
    name: Test Node
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: ['12', '14', '16']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      # Output which Node version is used
      - run: node --version

      # Install and test
      - run: npm install && npm run test-ci

  # Test different operating systems
  test-os:
    name: Test OS
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Output which Node version is used
      - run: node --version

      # Install and test
      - run: npm install && npm run test-ci
